# Generated by Django 4.0.6 on 2022-07-11 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('dev_language', models.CharField(choices=[('Python', 'Python'), ('Ruby', 'Ruby'), ('Java', 'Java'), ('C#', 'C#'), ('C++', 'C++'), ('Scala', 'Scala'), ('Golang', 'Golang'), ('Javascript', 'Javascript'), ('Groovy', 'Groovy')], max_length=30)),
            ],
        ),
    ]
