# Generated by Django 4.0.6 on 2022-07-11 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adept',
            name='dev_language',
            field=models.CharField(choices=[('Python', 'Python'), ('Ruby', 'Ruby'), ('Java', 'Java'), ('C#', 'C#'), ('C++', 'C++'), ('Scala', 'Scala'), ('Golang', 'Golang'), ('Javascript', 'Javascript'), ('Groovy', 'Groovy')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='adept',
            name='first_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='adept',
            name='last_name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
