# Generated by Django 4.0.6 on 2022-07-11 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_post', '0002_alter_adept_dev_language_alter_adept_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adept',
            name='dev_language',
            field=models.CharField(choices=[('Python', 'Python'), ('Ruby', 'Ruby'), ('Java', 'Java'), ('C#', 'C#'), ('C++', 'C++'), ('Scala', 'Scala'), ('Golang', 'Golang'), ('Javascript', 'Javascript'), ('Groovy', 'Groovy')], default='Python', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='adept',
            name='first_name',
            field=models.CharField(default='Python', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='adept',
            name='last_name',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
