# Generated by Django 4.0.6 on 2022-07-11 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_post', '0003_alter_adept_dev_language_alter_adept_first_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adept',
            options={'ordering': ['first_name']},
        ),
        migrations.AlterField(
            model_name='adept',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
